### ISSUE TITLE
Teamcanvas in Miro

### ISSUE THREAD

**Issue by Karima002** [DivaniNL/redpers-styleguide#18]
![Image](https://github.com/user-attachments/assets/9789852d-76ef-4370-934a-1620d2ce72c8)

[Link](https://miro.com/welcomeonboard/OEdjUzRoRmh3UHNsK3JlalFhbHppREdCTDBYOVlkSURQU1diVzZ0TE9mNkpaSnVPa1dEaXB2QzlhbVp3cnMvM21mYjZkTTVCV1p0R3lnbjlFOWJ1cFhreU0yTmhUZEJYc2J0dVRFYnpQcGQxZkN4UXBkN0ovTnZSL3BZRXJVUzEhZQ==?share_link_id=452622147445)

**Comment by Karima002** [comment]
![Image](https://github.com/user-attachments/assets/9789852d-76ef-4370-934a-1620d2ce72c8)

[Link](https://miro.com/welcomeonboard/OEdjUzRoRmh3UHNsK3JlalFhbHppREdCTDBYOVlkSURQU1diVzZ0TE9mNkpaSnVPa1dEaXB2QzlhbVp3cnMvM21mYjZkTTVCV1p0R3lnbjlFOWJ1cFhreU0yTmhUZEJYc2J0dVRFYnpQcGQxZkN4UXBkN0ovTnZSL3BZRXJVUzEhZQ==?share_link_id=452622147445)

**Comment by Mikiyas-hs** [comment]
.
