### ISSUE TITLE
typo 'sperator'

### ISSUE THREAD

**Issue by joostf** [DivaniNL/redpers-styleguide#26]
https://github.com/DivaniNL/look-and-feel-styleguide/blob/7c5e7d8a07e0518238d0476ca5aae9b7011f97a4/redpers.css#L403

**Comment by DivaniNL** [comment]
https://github.com/DivaniNL/redpers-styleguide/commit/d55df218744a7180ad28027baf68e5f3d60d4a96
opgelost :)
