### ISSUE TITLE
Nesting syntax error?

### ISSUE THREAD

**Issue by joostf** [DivaniNL/redpers-styleguide#27]
https://github.com/DivaniNL/look-and-feel-styleguide/blob/7c5e7d8a07e0518238d0476ca5aae9b7011f97a4/redpers.css#L410-L413

The &_primary doesn't seem to be a validely nested selector?!

**Comment by DivaniNL** [comment]
https://github.com/DivaniNL/look-and-feel-styleguide/commit/5f48bf122d3b17aa3ba32e871b49c6bbd6538b27
Dit is aangepast naar een classname
