### ISSUE TITLE
Geef de titel van je website een betekenisvolle naam

### ISSUE THREAD

**Issue by joostf** [DivaniNL/redpers-styleguide#28]
https://github.com/DivaniNL/look-and-feel-styleguide/blob/7c5e7d8a07e0518238d0476ca5aae9b7011f97a4/index.html#L6

Dit verschijnt in je tab, in zoekresultaten en in je favorieten.

**Comment by DivaniNL** [comment]
https://github.com/DivaniNL/look-and-feel-styleguide/commit/1f485c90eec114c984097e8d37f1a7a1027b7a25
Dit is toegevoegd
