### ISSUE TITLE
Onduidelijk hoe je de gedeelde stylesheet kunt gebruiken

### ISSUE THREAD

**Issue by krijnhoetmer** [DivaniNL/redpers-styleguide#32]
In de styleguide zelf staat geen link naar de gedeelde stylesheet. Probeer deze ook toe te voegen, zoals in het voorbeeld op https://github.com/fdnd-task/look-and-feel-styleguide/blob/main/index.html#L14-L18 — Hierdoor laat je andere developers zien hoe ze jullie styling kunnen gebruiken in hun project.

**Comment by DivaniNL** [comment]
https://github.com/DivaniNL/redpers-styleguide/blob/main/index.html#L18-L22
is toegevoegd

**Comment by Karima002** [comment]
Samen met @Mikiyas-hs naar Krijn gegaan voor extra uitleg over wat er precies met deze issue wordt bedoeld. De bedoeling dat een developer bij het bekijken van de styleguide direct kan zien waar de stylesheet geraadpleegd kan worden. De stylesheet is nu toegevoegd aan de website en ook aan de readme: 

Commit 163cbc2 (intro toegevoegd in HTML) en commit 2ddf826 (link toegevoegd aan Read me)
