### ISSUE TITLE
FORMS moeten nog afgemaakt worden

### ISSUE THREAD

**Issue by Mikiyas-hs** [DivaniNL/redpers-styleguide#33]

**Comment by DivaniNL** [comment]
@Mikiyas-hs  Ze staan in het gezamenlijke css bestand. Heb je het over de styleguide?

**Comment by DivaniNL** [comment]
https://divaninl.github.io/redpers-styleguide/#formulieren
Dit is nu gedaan.

https://github.com/DivaniNL/redpers-styleguide/blob/main/redpers.css#L397-L429 commit
